 "use client"
import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
import Navbar from './components/Navbar';
import './globals.css';

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({ duration: 1000 });
  }, []);

  return (
    <html lang="en">
      <head>
        <title>Microdose Muse</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
