"use client";
import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
import Navbar from './components/Navbar';
import './globals.css';
import Head from 'next/head';

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({ duration: 1000 });
  }, []);

  return (
    <html lang="en">
      <Head>
        <title>Microdose Muse</title>
        <link rel="preload" href="/assets/logo.webp" as="image" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
